### ISSUE TITLE
Cannot add children to Picker.Item

### ISSUE THREAD

**Issue by QnavWhat** [cccRaim/m-picker#1]
Using the example mentioned in the docu, I'm not able to make it run properly.

I tried the following ...

```
<Picker>
     <Picker.Item value="1" key="1">1</Picker.Item>
     <Pikcer.Item value="2" key="2">2</Picker.Item>
</Picker>
```

and face this error ...

```
Type '{ children: number; value: string; key: number; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; value: any; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; value: any; }'.ts(2322)
```

However using this ...

```
<Picker>
     <Picker.Item value="1" key="key" />
     <Picker.Item value="2" key="key" />
</Picker>
```

... won't create an error - but won't render the Item (renders empty Picker container).

I already use the 'rmc-picker' package and it is working fine. It would be awesome to have the key/scroll support coming with this package.
Hope anyone can help me out.

**Comment by cccRaim** [comment]
Fine, it's easy to fix.
I use js instead of ts before, so I'm not find this issue.
I will fix it in one hour.

**Comment by cccRaim** [comment]
fixed

**Comment by QnavWhat** [comment]
Works like a charm.
Just a subsequent question ... would it be possible to add support for scrolling via mouse wheel and/or key up/down?

**Comment by cccRaim** [comment]
> Works like a charm.
> Just a subsequent question ... would it be possible to add support for scrolling via mouse wheel and/or key up/down?

Well, it's mobile version. So I will not add this feature.
Or You can fork it and edit `src/Picker.tsx:132`, add `onscroll` and `keydown` event listener.

**Comment by cccRaim** [comment]
or pull request please, thx.
